plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@saithodev/semantic-release-backmerge"
    - backmergeBranches:
        - from: master
          to: development
      clearWorkspace: true
      backmergeStrategy: merge
      fastForwardMode: no-ff
      message: "chore(release): Preparations for next release [skip ci]"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"
  - "@semantic-release/github"
branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - "master"
  - name: "development"
    prerelease: "rc"
    channel: "false"
