[package]
name = "doclytics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
ollama-rs = "0.1.5"
reqwest = {version = "0.11.24", features = ["json"]}
serde_json = "1.0.108"
serde = "1.0.193"
substring = "1.4.5"

