name: Deploy Release
on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'
env:
  CI: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref }} # Assumes the tag name is the same as the ref. Adjust if necessary.
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        with:
          name: doclytics-${{ env.BRANCH_NAME }}-${{ matrix.os }}
          path: |
            ./target/${{ matrix.target }}/release/doclytics${{ matrix.os == 'windows-latest' && '.exe' || '' }}
      - name: Get Release Upload URL
        id: get_upload_url
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          upload_url=$(curl -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/${BRANCH_NAME} \
            | jq '.upload_url')
          echo ${upload_url}
          echo "UPLOAD_URL=${upload_url}" >> $GITHUB_OUTPUT
      - name: Upload Asset
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ASSET_PATH: ./target/${{ matrix.target }}/release/doclytics${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          ASSET_NAME: doclytics-${{ env.BRANCH_NAME }}-${{ matrix.os }}
          UPLOAD_URL: ${{ steps.get_upload_url.UPLOAD_URL }}
        run: |
          echo ${UPLOAD_URL}
          echo ${{ steps.get_upload_url.UPLOAD_URL }}
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/zip" --data-binary @$ASSET_PATH "${UPLOAD_URL}?name=${ASSET_NAME}&label=${ASSET_NAME}"
  build-docker:
    runs-on: ubuntu-latest
    if: ${{ github.ref }} != 'master' && ${{ github.ref }} != 'development'
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: production-artifacts
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/doclytics:${{ env.BRANCH_NAME }}
          platforms: linux/amd64,linux/arm64